# Generated by Django 5.1 on 2024-09-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
