# Generated by Django 5.1 on 2024-08-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_child_options_alter_hall_options_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='child',
        ),
        migrations.AddField(
            model_name='child',
            name='parents',
            field=models.ManyToManyField(blank=True, to='payments.parent'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
