version: '3.8'

services:
#  db:
#    image: postgres:14
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      POSTGRES_DB: your_db_name
#      POSTGRES_USER: your_db_user
#      POSTGRES_PASSWORD: your_db_password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  celery:
    build: .
    command: celery -A azarovProject worker --loglevel=info
    depends_on:
      - web

  celery-beat:
    build: .
    command: celery -A azarovProject beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - web
      - celery

  redis:
    image: redis:alpine

